In [234]:
import numpy as np
import pandas as pd

In [235]:
train=pd.read_csv('weatherAUS.csv')

In [298]:
X=train.drop(columns='Location')
X=X.drop(columns='Evaporation')
X=X.drop(columns='Sunshine')
X=X.drop(columns='RainTomorrow')
X=X.drop(columns='Date')
Y=train['RainTomorrow']

In [299]:
X.head(2)


MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed WindDir9am  \
0     13.4     22.9       0.6           W           44.0          W   
1      7.4     25.1       0.0         WNW           44.0        NNW   

  WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0        WNW          20.0          24.0         71.0         22.0   
1        WSW           4.0          22.0         44.0         25.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm RainToday  
0       1007.7       1007.1       8.0       NaN     16.9     21.8        No  
1       1010.6       1007.8       NaN       NaN     17.2     24.3        No

In [300]:
from sklearn import preprocessing
le= preprocessing.LabelEncoder()
cols=["WindDir9am","WindDir3pm",'WindGustDir','Cloud9am','Cloud3pm','RainToday']
for i in cols :
    X[i]= le.fit_transform(X[i]) # fit label encoder and return encoder labels
     #transform label to normalized encoding
    
    print(le.classes_) #preprocessing the features without char

['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW' nan]
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW' nan]
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW' nan]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
['No' 'Yes' nan]


In [301]:
train['RainTomorrow']=le.fit_transform(train['RainTomorrow'])
print(Y.head(2))

0    0
1    0
Name: RainTomorrow, dtype: int64


In [302]:
from sklearn.model_selection import train_test_split #split our data


In [303]:
from sklearn.linear_model import  SGDClassifier


In [304]:
model = SGDClassifier()

In [306]:
X=X.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
Y=Y.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)

In [307]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y ,random_state=1)

I used Stochastic Gradient Descent cz for BIG DATA Gradient descent is slowwwwww SGD reduces the number of terms


---
For example : if we have 10000 samples then SGD would reduce the amount terms computed by a factor of 10000 :)



In [308]:
model.fit(X_train,y_train)

SGDClassifier()

In [309]:
model.score(X_train,y_train)

0.8074040973463495

In [310]:
model.predict(X_train)

array([0, 0, 0, ..., 0, 0, 0])

In [311]:
from sklearn.metrics  import  mean_squared_error

In [312]:
predicted_y = model.predict(X_test)

In [313]:
mean_squared_error(y_test, predicted_y)

0.24666575003437372

In [257]:
a="4 5 6"
h=a.split(' ')
for i in range(0,len(h)-3):
  h.append(int(h[i]))
h=np.array(h)
h

array(['4', '5', '6'], dtype='<U1')

In [314]:
train.head(2)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   

   RainTomorrow  
0             0  
1             0  

[2 rows x 23 columns]

In [259]:
X_test.head(1)

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
136354      7.6     29.3       0.0            3           35.0           3   

        WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
136354           7          24.0          17.0         10.0          5.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
136354       1018.2       1014.2         0         1     22.1     28.3   

        RainToday  RainTomorrow  
136354          0             0

convert to 2 dimensioal array 

In [315]:
y_pred=model.predict(X_test)

In [316]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [317]:
y_test = np.array(y_test,dtype=float)

In [318]:
y_test.reshape(-1,1)
y_pred.reshape(-1,1)

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [319]:
test=[]
for i in range(0,len(y_test)) :
    test.append(int(y_test[i]))
  

In [320]:
test=np.array(test)

In [321]:
test

array([0, 0, 1, ..., 0, 0, 0])

### **Testinggggggggg**

In [322]:
from sklearn.metrics import accuracy_score
df = {} 
accuracy_score(y_test,y_pred) #we can do bettre maybe if we change the model /reduce features

0.8081946926990238

In [324]:
df = np.concatenate((y_pred.reshape(-1,1),test.reshape(-1,1)),axis=1)
dataframe = pd.DataFrame(df,columns=['Predicitions','True or false'])

In [325]:
dataframe

Predicitions  True or false
0                 0              0
1                 0              0
2                 0              1
3                 0              0
4                 0              0
...             ...            ...
29087             0              0
29088             0              0
29089             0              0
29090             0              0
29091             0              0

[29092 rows x 2 columns]