In [234]:
import numpy as np
import pandas as pd

In [235]:
train=pd.read_csv('weatherAUS.csv')

In [236]:
X=train.drop(columns='Location')
X=X.drop(columns='Evaporation')
X=X.drop(columns='Sunshine')
Y=X['RainTomorrow']

In [237]:
X.head(2)


Date  MinTemp  MaxTemp  Rainfall WindGustDir  WindGustSpeed  \
0  2008-12-01     13.4     22.9       0.6           W           44.0   
1  2008-12-02      7.4     25.1       0.0         WNW           44.0   

  WindDir9am WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0          W        WNW          20.0          24.0         71.0         22.0   
1        NNW        WSW           4.0          22.0         44.0         25.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8        No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3        No   

  RainTomorrow  
0           No  
1           No

In [238]:
from sklearn import preprocessing
le= preprocessing.LabelEncoder()
cols=["WindDir9am","WindDir3pm",'WindGustDir','Cloud9am','Cloud3pm','RainToday']
for i in cols :
    X[i]= le.fit_transform(X[i]) # fit label encoder and return encoder labels
     #transform label to normalized encoding
    
    print(le.classes_) #preprocessing the features without char

['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW' nan]
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW' nan]
['E' 'ENE' 'ESE' 'N' 'NE' 'NNE' 'NNW' 'NW' 'S' 'SE' 'SSE' 'SSW' 'SW' 'W'
 'WNW' 'WSW' nan]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
['No' 'Yes' nan]


In [239]:
train['RainTomorrow']=le.fit_transform(train['RainTomorrow'])
print(Y.head(2))

0    No
1    No
Name: RainTomorrow, dtype: object


In [240]:
from sklearn.model_selection import train_test_split #split our data


In [241]:
from sklearn.linear_model import  SGDClassifier


In [242]:
model = SGDClassifier()

In [248]:
X.head(2)
X.head(2)

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
0          13.4     22.9       0.6           13           44.0          13   
1           7.4     25.1       0.0           14           44.0           6   
2          12.9     25.7       0.0           15           46.0          13   
3           9.2     28.0       0.0            4           24.0           9   
4          17.5     32.3       1.0           13           41.0           1   
...         ...      ...       ...          ...            ...         ...   
145455      2.8     23.4       0.0            0           31.0           9   
145456      3.6     25.3       0.0            6           22.0           9   
145457      5.4     26.9       0.0            3           37.0           9   
145458      7.8     27.0       0.0            9           28.0          10   
145459     14.9      0.0       0.0           16            0.0           2   

        WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
0               14          20.0          24.0         71.0         22.0   
1               15           4.0          22.0         44.0         25.0   
2               15          19.0          26.0         38.0         30.0   
3                0          11.0           9.0         45.0         16.0   
4                7           7.0          20.0         82.0         33.0   
...            ...           ...           ...          ...          ...   
145455           1          13.0          11.0         51.0         24.0   
145456           3          13.0           9.0         56.0         21.0   
145457          14           9.0           9.0         53.0         24.0   
145458           3          13.0           7.0         51.0         24.0   
145459           2          17.0          17.0         62.0         36.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0            1007.7       1007.1         8        10     16.9     21.8   
1            1010.6       1007.8        10        10     17.2     24.3   
2            1007.6       1008.7        10         2     21.0     23.2   
3            1017.6       1012.8        10        10     18.1     26.5   
4            1010.8       1006.0         7         8     17.8     29.7   
...             ...          ...       ...       ...      ...      ...   
145455       1024.6       1020.3        10        10     10.1     22.4   
145456       1023.5       1019.1        10        10     10.9     24.5   
145457       1021.0       1016.8        10        10     12.5     26.1   
145458       1019.4       1016.5         3         2     15.1     26.0   
145459       1020.2       1017.9         8         8     15.0     20.9   

        RainToday RainTomorrow  
0               0           No  
1               0           No  
2               0           No  
3               0           No  
4               0           No  
...           ...          ...  
145455          0           No  
145456          0           No  
145457          0           No  
145458          0           No  
145459          0            0  

[145460 rows x 19 columns]

In [249]:
X=X.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
Y=Y.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)

In [250]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,stratify=Y ,random_state=1)

TypeError: ignored

I used Stochastic Gradient Descent cz for BIG DATA Gradient descent is slowwwwww SGD reduces the number of terms


---
For example : if we have 10000 samples then SGD would reduce the amount terms computed by a factor of 10000 :)



In [251]:
model.fit(X_train,y_train)

SGDClassifier()

In [252]:
model.score(X_train,y_train)

0.7818128695173931

In [253]:
model.predict(X_train)

array([0, 0, 0, ..., 0, 0, 0])

In [254]:
from sklearn.metrics  import  mean_squared_error

In [255]:
predicted_y = model.predict(X_test)

In [256]:
mean_squared_error(y_test, predicted_y)

0.2615495668912416

In [257]:
a="4 5 6"
h=a.split(' ')
for i in range(0,len(h)-3):
  h.append(int(h[i]))
h=np.array(h)
h

array(['4', '5', '6'], dtype='<U1')

In [258]:
train.head(2)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1  2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0           W           44.0          W  ...        71.0         22.0   
1         WNW           44.0        NNW  ...        44.0         25.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8         No   
1       1010.6       1007.8       NaN       NaN     17.2     24.3         No   

   RainTomorrow  
0             0  
1             0  

[2 rows x 23 columns]

In [259]:
X_test.head(1)

MinTemp  MaxTemp  Rainfall  WindGustDir  WindGustSpeed  WindDir9am  \
136354      7.6     29.3       0.0            3           35.0           3   

        WindDir3pm  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
136354           7          24.0          17.0         10.0          5.0   

        Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
136354       1018.2       1014.2         0         1     22.1     28.3   

        RainToday  RainTomorrow  
136354          0             0

convert to 2 dimensioal array 

In [260]:
y_pred=model.predict(X_test)

In [261]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [262]:
y_test = np.array(y_test,dtype=float)

In [ ]:
y_test.reshape(-1,1)
y_pred.reshape(-1,1)

In [264]:
test=[]
for i in range(0,len(y_test)) :
    test.append(int(y_test[i]))
  

In [265]:
test=np.array(test)

In [266]:
test

array([0, 0, 1, ..., 0, 0, 0])

### **Testinggggggggg**

In [271]:
from sklearn.metrics import accuracy_score
df = {}
accuracy_score(y_test,y_pred) #we can do bettre maybe if we change the model /reduce features

0.7825862780145745

In [267]:
df = np.concatenate((y_pred.reshape(-1,1),test.reshape(-1,1)),axis=1)
dataframe = pd.DataFrame(df,columns=['Predicitions','True or false'])

In [268]:
dataframe

Predicitions  True or false
0                 0              0
1                 0              0
2                 0              1
3                 0              0
4                 0              0
...             ...            ...
29087             0              0
29088             0              0
29089             0              0
29090             0              0
29091             0              0

[29092 rows x 2 columns]